### ISSUE TITLE
Add addional available information to response from assaytype/assayname endpoints

### ISSUE THREAD

**Issue by shirey** [dbmi-pitt/ubkg#68]
Add additional information to the responses for the `/assaytype` and `/assayname` endpoints that were added to mimic the old versions in search-api.  These additions are based on additional information included in the the HuBMAP Application Ontology for data/assay types which isn't available in the old assay_types.yaml file in search-api.

**Comment by AlanSimmons** [comment]
@shirey Can we close this?

**Comment by AlanSimmons** [comment]
@shirey 

The dataset_provider attribute from the ontology could be added to the reponses of the _/assaytype_ and _/assayname_ endpoints. 

The current endpoints simply reflect what is in the current assay_types.yaml file, their returns will correspond to the following:
```
cell-dive:
    description: Cell DIVE
    alt-names: ["cell DIVE", "Cell DIVE"]
    primary: true
    contains-pii: false

celldive_deepcell:
    description: CellDIVE [DeepCell + SPRM]
    alt-names: []
    primary: false
    contains-pii: false
    vitessce-hints: ['sprm', 'anndata', 'is_image', 'is_tiled']
```
The _datasets_ endpoint of the UBKG API returns information such as the following. 
The difference between the two is the dataset_provider field, which is in the ontology but not the assay_types.yaml file.

```
{
        "alt-names": [
            "Cell DIVE",
            "cell DIVE"
        ],
        "contains-pii": false,
        "data_type": "cell-dive",
        "dataset_provider": "HuBMAP IEC",
        "description": "Cell DIVE",
        "primary": true,
        "vis-only": false,
        "vitessce-hints": []
    },
    {
        "alt-names": [],
        "contains-pii": false,
        "data_type": "celldive_deepcell",
        "dataset_provider": "HuBMAP IEC",
        "description": "CellDIVE [DeepCell + SPRM]",
        "primary": false,
        "vis-only": false,
        "vitessce-hints": [
            "is_tiled",
            "is_image",
            "anndata",
            "sprm"
        ]
    },
```
